version: "3"

services:
  mysqlserver:
    container_name: mysqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    #image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=01234567aA # TODO set as sys env
      - ACCEPT_EULA=Y
    ports:
      - "1433"

  myhotel:
    container_name: haas
    build: .
    command:
      - /bin/sh
      - -c
      - |
        ../wait-for-it.sh mysqlserver:1433 -- echo "UP and RUN"
        dotnet HaaS-API.dll --urls=http://0.0.0.0:5167
    ports: 
      - "0.0.0.0:5167:5167"
    depends_on:
      - "mysqlserver"
